site_name: Raghav Saboo's Wiki
site_url: https://docs.raghavsaboo.com
plugins:
  - search
  # - mkdocs-jupyter:
  #     include_requirejs: true
  #     remove_tag_config:
  #         remove_input_tags:
  #             - hide_input
  - mknotebooks:
      enable_default_jupyter_cell_styling: false
      enable_default_pandas_dataframe_styling: false
  - inline-svg
  - offline
  - glightbox
  - awesome-pages
theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - search.highlight
    - search.share
    - navigation.tabs
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    # - navigation.prune
    - toc.follow
    - navigation.top
    - header.autohide
  palette:
    primary: white
    accent: light blue
  logo: assets/profile.png
  favicon: assets/profile.png
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx.inline
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.keys
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - abbr
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes
  - pymdownx.critic
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - meta
  - codehilite
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
copyright: Copyright &copy; 2024 Raghav Saboo
extra:
  generator: false
  analytics:
    provider: google
    property: G-3BR421QVX9